### ISSUE TITLE
anyone of these paper have shared code for repeat  experiments?

### ISSUE THREAD

**Issue by hurun** [benedekrozemberczki/awesome-fraud-detection-papers#1]
Thank you for your work to gather them here , its awsome and very usefull.
but any of these paper have shared code to research experiments, if can find some of code it would be helpful for research.
thanks your work

**Comment by benedekrozemberczki** [comment]
Hi there,

I looked for it but seems that they did not share their code. These papers all seem to be fairly easy to implement. Dataset-wise it seems to be a complicated problem -- they use their own private datasets.

Benedek

**Comment by hurun** [comment]
Thanks for your reply. 
I am a graduate student. I have done some similar work recently,  and the experimental results look very good. I want to compare with a paper "Online Reputation Fraud Campaign Detection in User Ratings", but it should be a big challenge for me to repeat this paper at present.
It would be very helpful for me if the paper have open code sharing.

**Comment by benedekrozemberczki** [comment]
You can always contact them. Researchers can be quite nice people.

**Comment by hurun** [comment]
I once wrote an email to contact the author, but did not receive a reply .
I went to check the mailbox just now, but I still didn't receive it.
its a sad story.
