### ISSUE TITLE
DB/netsci papers

### ISSUE THREAD

**Issue by szarnyasg** [benedekrozemberczki/awesome-fraud-detection-papers#2]
Hello @benedekrozemberczki,

I've been working on graph-based fraud detection techniques with my Master's student @kerimovscreations

We found a couple of papers that could be a good fit for your list. In decreasing order of interest:

* [Real-time Constrained Cycle Detection in Large Dynamic Graphs](http://www.vldb.org/pvldb/vol11/p1876-qiu.pdf), VLDB 2018
* [A graph-based, semi-supervised, credit card fraud detection system](https://link.springer.com/chapter/10.1007/978-3-319-50901-3_57), COMPLEX NETWORKS 2016 [[OA]](http://www.oliviercaelen.be/doc/IEAAIE_2017_Finalversion-PDF_39.pdf)
* [Improving Card Fraud Detection Through Suspicious Pattern Discovery](https://link.springer.com/chapter/10.1007%2F978-3-319-60045-1_21), IEA/AIE 2017 [[OA]](http://www.oliviercaelen.be/doc/GBSSCCFDS.pdf)

Are there any criteria for including a paper, e.g. are database systems papers such as the VLDB one of interest?

**Comment by benedekrozemberczki** [comment]
Dear @szarnyasg,

I will add these to the repository. Feel free to open a PR if you want to.

Benedek
